# Shell variables
# Generated by 'wal'
wallpaper="{wallpaper}"

# Special
background='{background}'
foreground='{foreground}'
cursor='{cursor}'
alpha='{alpha}'

# Colors
color0='{color0}'
color1='{color1}'
color2='{color2}'
color3='{color3}'
color4='{color4}'
color5='{color5}'
color6='{color6}'
color7='{color7}'
color8='{color8}'
color9='{color9}'
color10='{color10}'
color11='{color11}'
color12='{color12}'
color13='{color13}'
color14='{color14}'
color15='{color15}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:15,bg:-1,hl:3,fg+:7,bg+:8,hl+:3
    --color info:7,prompt:2,spinner:6,pointer:6,marker:2
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${{LS_COLORS}}:su=30;41:ow=30;42:st=30;44:"

