#! /bin/sh

. $HOME/.config/colors.sh

SXHKD_CONFIGS=(
  $HOME/.config/sxhkd/sxhkdrc
)

for f in $HOME/.config/sxhkd/?*; do
  if [[ ! "$f" =~ "sxhkdrc" ]]; then
    SXHKD_CONFIGS+=($f)
  fi
done

SXHKD_FIFO=/tmp/sxhkd-key-fifo
mkfifo $SXHKD_FIFO
sxhkd -s $SXHKD_FIFO "${SXHKD_CONFIGS[@]}" &
sxhkd-chord-color -f $SXHKD_FIFO -c "$color5" &

bspwm-urgent-border "$color9" &

$HOME/.config/polybar/launch.sh

bspc monitor -d 1

bspc config border_width         4
bspc config window_gap           5

bspc config focused_border_color "$color4"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc config initial_polarity second_child
bspc config automatic_scheme alternate

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config pointer_action1 resize_side
bspc config pointer_action3 move

bspc rule -a mpv state='floating'
bspc rule -a feh state='floating' center='on'
bspc rule -a '*:info-term' state='floating' center='on'
bspc rule -a '*:info-term-large' state='floating' center='on' rectangle='1000x800+0+0'
